### ISSUE TITLE
Need more steps for contract installation in readme

### ISSUE THREAD

**Issue by migui3230** [scio-labs/inkathon#10]
I was getting errors when trying to run the cargo install step 3 in the readme, needed to go to substrates installation docs and install everything there before I could run step 3's cargo install

**Comment by wottpal** [comment]
Hey @migui3230, thanks for your time trying out this boilerplate. Glad you fixed it, what was the specific command that was missing? I'm unsure how detailed the instructions here should get (I'm already linking to https://docs.substrate.io/install/ for a complete install). Instead, it probably makes more sense to have a plug-and-play docker container ready that can compile the latest ink! contracts. What do you think?

And also more generally, how was your experience with the boilerplate after this? Open for more feedback 🙌

**Comment by migui3230** [comment]
I was missing `rustup nightly` and `openssl` which i found through the substrate docs.

A plug-and-play docker container would be awesome and provide a much smoother experience 👀
