### ISSUE TITLE
[SL-13] Add loading animation for update greeting & only show success on finish

### ISSUE THREAD

**Issue by wottpal** [scio-labs/inkathon#13]
See https://github.com/scio-labs/inkathon/pull/12#issuecomment-1436668012

<sub>[SL-13](https://linear.app/scio/issue/SL-13/add-loading-animation-for-update-greeting-and-only-show-success-on)</sub>

**Comment by nicolad** [comment]
hey @wottpal, I also was thinking about of animation after connect button is clicked and wallet is loaded.
What do u think to use `framer-motion` or `react-spring`, not sure what's the latest react state-of-art solution 🤣

**Comment by wottpal** [comment]
there already should be a loading animation on the "connect wallet" button 🤔 is it not displaying for you?

for the animation, as i'm just using chakra-ui in the repo, i can just give the button component a `loading={true}` to get a spinner

**Comment by wottpal** [comment]
Closed via https://github.com/scio-labs/inkathon/commit/d7346e890e6cd3540f35905ce2412990011ef8e9
