### ISSUE TITLE
`#![feature]` may not be used on the stable release channel

### ISSUE THREAD

**Issue by ganesh1997oli** [scio-labs/inkathon#16]
on adding openbrush latest version which is suitable for latest ink 4.0.0 release doesn't work on inkathon `greeter contract` build with `pnpm build` and throws below error but on running with +nightly works fine. I have checked on freshly created ink project no issue there.
```
openbrush = { tag = "3.0.0", git = "https://github.com/727-Ventures/openbrush-contracts", default-features = false, features = [
    "psp22",
] }
```

<img width="1440" alt="Screenshot 2023-02-21 at 20 54 47" src="https://user-images.githubusercontent.com/42571338/220383031-bb47e63d-4fee-4e1d-83de-e862fe4b7e45.png">

**Comment by wottpal** [comment]
Yeah you are right :) Good catch! But I think this is not related to ink!athon. If you require the nightly toolchain, just switch to it. ink! v4 doesn't require it by default so I wouldn't set it as the default tbh.

Just replace `stable` with `nightly` in `packages/contracts/rust-toolchain` (just tested it successfully).
