### ISSUE TITLE
Error while connecting to Polkadot.js wallet

### ISSUE THREAD

**Issue by poppyseedDev** [scio-labs/inkathon#20]
![image](https://github.com/scio-labs/inkathon/assets/30662672/3cea510d-ab80-4a87-b453-c0adc4495e48)

**Comment by poppyseedDev** [comment]
Solved the error.. The error that I was encountering was an incorrect address length of 20 bytes, while the expected length of address is 32 bytes. One of the accounts I had in the Polkadot.js wallet was of incorrect length, when I removed it, the application afterwards works fine.
Although still doesn't work on https://inkathon.xyz/ probably because of cache

**Comment by wottpal** [comment]
Thanks for reporting, @poppyseedDev! You might need to forget the website in the extension manually or clear cache (or both) 🤔

Can you provide me a guide on how I can try this out myself (i.e. how do i create an invalid account in polkadot.js). Then I might be able to place a try-catch block at the appropriate place.
