### ISSUE TITLE
Migrate to shadcn/ui components & vanilla tailwind

### ISSUE THREAD

**Issue by wottpal** [scio-labs/inkathon#22]
- [x] Change file naming convention to kebab-case
- [x] Integrate `shadcn/ui` components (via CLI)
- [x] Setup plain tailwind with `twin-merge`, `cva`, and the `cn` helper
- [x] Migrate [all components](https://github.com/scio-labs/inkathon/tree/main/packages/frontend/src/components)
- [x] Remove `twin.macro` & `chakra-ui` dependencies

**Comment by ical10** [comment]
This issue is related to #21, so I'll work on both for the migration.
