### ISSUE TITLE
Dockerfile for development & optional deployment

### ISSUE THREAD

**Issue by wottpal** [scio-labs/inkathon#29]
- [ ] Dockerfile for local development of contracts & frontend (Rust Setup, Contract Deployment, Next.js Startup & Watching)
- [ ] Dockerfile for Next.js non-Vercel deployments

**Comment by nraychaudhuri** [comment]
Hi @wottpal I want to work on this issue.

**Comment by wottpal** [comment]
Hey @nraychaudhuri would be amazing if you want to support on this! 🙌

Added some more info and am happy to discuss everything! (We also have a TG group: https://t.me/inkathon)

**Comment by wottpal** [comment]
Hey @nraychaudhuri, are you still interested in doing it? It doesn't has to be super quick, just want to know if i should assign it to someone else :)
