### ISSUE TITLE
Replace React Hot Toast with Sonner

### ISSUE THREAD

**Issue by wottpal** [scio-labs/inkathon#34]
https://github.com/emilkowalski/sonner

**Comment by ical10** [comment]
Any particular reason for the switch to Sonner? @wottpal

**Comment by wottpal** [comment]
Love the stacking and smaller 🫠

**Comment by ical10** [comment]
Sounds good, will do the replacement.

**Comment by wottpal** [comment]
Decided against in favor of other issues for now
