### ISSUE TITLE
pre-requisites starter script

### ISSUE THREAD

**Issue by muddlebee** [scio-labs/inkathon#51]
https://github.com/scio-labs/inkathon?tab=readme-ov-file#2-build--deploy-contracts-on-a-local-node

![image](https://github.com/scio-labs/inkathon/assets/8139783/ab072209-429f-4231-81b6-381a80149db3)

script to automate installation of all the pre-requisites

**Comment by muddlebee** [comment]
for [substrate-contracts-node](https://github.com/paritytech/substrate-contracts-node)

can write a script to fetch the binary and untar it from https://github.com/paritytech/substrate-contracts-node/releases and can run directly from the binary
` ./substrate-contracts-node --dev`

**Comment by wottpal** [comment]
Hey @muddlebee, great suggestion. May I ask what platform you are running on? In my experience it's quite hard to get such scripts right (w/o lots of efforts) and work seemlessly in different environments (operating systems, rust versions, shells, etc.). Wdyt?

**Comment by muddlebee** [comment]
@wottpal I use wsl. Yes you are right quite tedious to maintain such utility script.

However we can add commands for cargo contract installation and for cargo contract node it can downloaded the latest binary and run it for local simulation.

**Comment by ical10** [comment]
This might be solved using the Dockerfile for contracts [here](https://github.com/scio-labs/inkathon/pull/50). You can just run the Dockerfile regardless of the platform you're running on.

**Comment by wottpal** [comment]
That's actually a good point, @ical10! Will close this.
