### ISSUE TITLE
Deploy command line instruction don't work

### ISSUE THREAD

**Issue by Boyquotes** [scio-labs/inkathon#63]
When I follow the readme step configuration, the deploy script command don't exist ( and no reference in package.json )

```
# Deploy the contracts on the local node
pnpm run deploy
```

**Comment by wottpal** [comment]
> When I follow the readme step configuration, the deploy script command don't exist ( and no reference in package.json )
> 
> ```
> # Deploy the contracts on the local node
> pnpm run deploy
> ```

Hey, have you `cd`'ed into `/contracts` and are also running a local node (`pnpm run node`) in parallel?

**Comment by Boyquotes** [comment]
Hey, sometime I am a copy/paste dev 😅 
It's logic but other command are made on the root folder, may be write to move to the contract directory in the readme.md is a good idea. If you are ok, I made a pull request to add that :

# Go to the contracts/ directory and deploy the contracts on the local node
cd contracts/
pnpm run deploy

**Comment by wottpal** [comment]
🫡 ✅

![CleanShot 2024-04-17 at 11 14 17@2x](https://github.com/scio-labs/inkathon/assets/3930150/f605ca89-3bbc-4276-9b2a-79f6f54332a4)
