### ISSUE TITLE
webpack and docker-compose up error for the frontend 

### ISSUE THREAD

**Issue by stan-dot** [scio-labs/inkathon#65]
` ERROR [frontend-prod builder 1/1] RUN NEXT_BUILD_STANDALONE=true pnpm --filter='*frontend' build  && pnpm --filter='*frontend' deploy pruned -  27.5s
------
 > [frontend-prod builder 1/1] RUN NEXT_BUILD_STANDALONE=true pnpm --filter='*frontend' build  && pnpm --filter='*frontend' deploy pruned --prod:
8.166 
8.166 > @inkathon/frontend@0.8.0 build /app/frontend
8.166 > NODE_ENV=production next build
8.166 
9.318 Attention: Next.js now collects completely anonymous telemetry regarding usage.
9.318 This information is used to shape Next.js' roadmap and prioritize features.
9.318 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
9.318 https://nextjs.org/telemetry
9.318 
9.865   ▲ Next.js 14.2.3
9.865   - Environments: .env.local
9.865 
10.28    Creating an optimized production build ...
11.90 
11.90 (process:37): VIPS-WARNING **: 20:02:53.317: threads clipped to 1024
23.87 Failed to compile.
23.87 
23.87 ./src/app/page.tsx
23.87 Module not found: Can't resolve '@/app/components/home-page-title'
23.87 
23.87 https://nextjs.org/docs/messages/module-not-found
23.87 
23.87 ./src/app/page.tsx
23.87 Module not found: Can't resolve '@/components/web3/chain-info'
23.87 
23.87 https://nextjs.org/docs/messages/module-not-found
23.87 
23.87 ./src/app/page.tsx
23.87 Module not found: Can't resolve '@/components/web3/connect-button'
23.87 
23.87 https://nextjs.org/docs/messages/module-not-found
23.87 
23.87 ./src/app/page.tsx
23.87 Module not found: Can't resolve '@/components/web3/greeter-contract-interactions'
23.87 
23.87 https://nextjs.org/docs/messages/module-not-found
23.87 
23.87 ./src/app/providers.tsx
23.87 Module not found: Can't resolve '@/deployments/deployments'
23.87 
23.87 https://nextjs.org/docs/messages/module-not-found
23.87 
23.89 
23.89 > Build failed because of webpack errors
23.90 /app/frontend:
23.90  ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @inkathon/frontend@0.8.0 build: `NODE_ENV=production next build`
23.90 Exit status 1
------
failed to solve: process "/bin/sh -c NEXT_BUILD_STANDALONE=true pnpm --filter='*frontend' build  && pnpm --filter='*frontend' deploy pruned --prod" did not complete successfully: exit code: 1`

OS: Windows 11 with Ubuntu 20.04
Docker Desktop version Current version: 4.28.0 (139021)

**Comment by ical10** [comment]
Hi @stan-dot 

I can't reproduce the issue. After a quick search, this might be something worth to try on your end: https://stackoverflow.com/a/76682018

**Note:** Just to make sure, did you try to follow the steps written here? https://github.com/scio-labs/inkathon/pull/50
I'd suggest using Orbstack instead of Docker desktop, because I was having intermittent issues with it.
