### ISSUE TITLE
CLI for scaffolding project structure

### ISSUE THREAD

**Issue by wottpal** [scio-labs/inkathon#8]
Create a CLI tool that creates a full ready-to-use ink!athon monorepo app structure. With a command like `npm create create-inkathon-app`.

Potential options:
* Package Name
* Project Name
* pnpm/yarn/npm (will have to check first which of those works nicely with the monorepo)
* TS/JS (will keep it probably ts-only)
* prettier/eslint/husky
* Twin/Tailwind/Chakra
* Default Chain
* Install Rust/cargo (probably too error-prone)

See https://github.com/facebook/create-react-app & https://github.com/t3-oss/create-t3-app for inspiration.

**Comment by nicolad** [comment]
@wottpal u already might know:

https://turbo.build/repo

**Comment by wottpal** [comment]
Thanks for sharing! I actually do use turbo repo in some of my projects but didn't find any information about their tools for scaffolding CLIs? It always assumes the project is already in existence.

**Comment by nicolad** [comment]
I guess this is their tool:

https://github.com/vercel/turbo/tree/main/packages/create-turbo
